In [62]:
import numpy as np
import pandas as pd
import tensorflow as tf
import sklearn
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import pickle

In [63]:

iris = datasets.load_iris(as_frame=True)
print(iris.frame.head())
print(iris.frame.info())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int6

In [64]:
print(sklearn.__version__)



1.8.0


In [65]:
X,y=iris.data,iris.target


X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [66]:
model=RandomForestClassifier(n_estimators=200)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print("raport klasyfikacji:")
print(classification_report(y_test,y_pred, target_names=iris.target_names))
print("macierz pomyłek")
print(confusion_matrix(y_test,y_pred))

raport klasyfikacji:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

macierz pomyłek
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [67]:
with open('model_iris_v2.pkl', 'wb') as f:
    pickle.dump(model, f)